In [9]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('uiuc-gpa-dataset.csv')

df = df.rename(columns={'Course Title': 'Course_Title'})
df = df.rename(columns={'Primary Instructor': 'Primary_Instructor'})
df

,Year,Term,YearTerm,Subject,Number,Course_Title,Sched Type,A+,A,A-,...,B-,C+,C,C-,D+,D,D-,F,W,Primary_Instructor
0,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,2,14,2,...,3,0,1,0,0,0,0,0,0,"Zheng, Reanne"
1,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,15,0,...,1,0,2,0,0,0,0,1,0,"Atienza, Paul Michael L"
2,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,OD,7,4,1,...,0,2,3,0,0,1,0,1,0,"Wang, Yu"
3,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,1,18,0,...,1,0,0,0,0,0,0,0,0,"Zheng, Reanne"
4,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,16,1,...,1,0,2,0,0,0,0,0,0,"Atienza, Paul Michael L"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61552,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,0,1,3,0,0,0,2,1,"Stepanov, Alexei G"
61553,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,0,0,"Unger, David"
61554,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,7,5,1,1,0,2,0,1,0,"Morgan, William T"
61555,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,0,3,3,2,0,0,1,1,0,"Ott-Monsivais, Stephanie"
61556,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,1,0,4,0,0,1,0,2,0,"Keane, Richard D"

In [10]:
def input_class():
    class_string = input("Enter Class >>>")
    num = int(class_string.split()[1])
    name = class_string.split(' ')[0]
    return num,name

def linegraph(gpa, num_students, proff):
    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    ax.plot(gpa, num_students, color='tab:blue')
    ax.set_title(proff)
    plt.show()

def scatterPlot(gpa, num_students, proffs):
    fig, ax = plt.subplots()
    for prof in proffs:
        scale = 200.0 * np.random.rand(n)
        ax.scatter(x, y, c=color, s=scale, label=color,
               alpha=0.3, edgecolors='none')

def sort_by_instructor():
    proffs = new_df.Primary_Instructor.unique()
    print(proffs)
    for prof in proffs:
        df_byProff = (df.loc[(df['Primary_Instructor'] == prof) ])
    
        new = df_byProff.sum(axis = 0, skipna = True)
        num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00, 0.00]

def sort_by_year():
    years = new_df.Year.unique()
    print(years)
    total = 0
    for year in years:
        df_year = (df.loc[(df['Year'] == year) ])
    
        new = df_year.sum(axis = 0, skipna = True)
        num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00, 0.00]
        total = sum(num_students) + total
    print(total)

def cumulative(num_students):
    total = 0 
    cum = []
    for i in range(13):
        if i == 0:
            cum.append(num_students[13-i])
            
        cum.append(num_students[13-i] + cum[13-1])
        cum.reverse
    return cum

In [11]:
#user input    
num,sub = input_class()
#sort by class
new_df = (df.loc[(df['Number'] == num)  & (df['Subject'] == sub)])
#list of years
years = new_df.Year.unique()
years.sort()
avg = 0
for year in years:
    df_year = (new_df.loc[(df['Year'] == year) ])
  
    new = (df_year.sum(axis = 0, skipna = True))
    #print(df_year)
    
    num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
    gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00]
    total = sum(num_students, 0)
    
    weighted_sum = []
    for i in range(len(gpa)):
        weighted_sum.append(num_students[i]*gpa[i])
    avg_gpa = sum(weighted_sum) / total
    As = num_students[0] / total

    #print("Average GPA of Year {}: {} and % of students getting 4.00 is {} and total number of students are {}".format(year, avg_gpa, As, total))
    avg = avg + avg_gpa
    
new_df

#print("Average" + str(avg / len(years)))

Empty DataFrame
Columns: [Year, Term, YearTerm, Subject, Number, Course_Title, Sched Type, A+, A, A-, B+, B, B-, C+, C, C-, D+, D, D-, F, W, Primary_Instructor]
Index: []

[0 rows x 22 columns]

In [12]:
number,name = input_class()
name = name.upper()

new_df = df.loc[(df['Number'] == number)  & (df['Subject'] == name)]
years = new_df.YearTerm.unique()
years.sort()
instructors = new_df.Primary_Instructor.unique()

#
for i in range(len(years)):
    df_year = new_df.loc[(new_df['YearTerm'] == years[i])]
    instructors = df_year.Primary_Instructor.unique()
    for instructor in instructors:
        #print(i)
        #print(years[i])
        #df_year = new_df.loc[(new_df['Primary_Instructor'] == instructor) & (new_df['Year'] == years[i])]
        #df_year = new_df.loc[& (new_df['Year'] == year)]
        df_instructor = df_year.loc[(df_year['Primary_Instructor']) == instructor]
        new = (df_instructor.sum(axis = 0, skipna = True))
        
        #print(df_year)
    
        num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        
        gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00]
        total = sum(num_students, 0)
    
        weighted_sum = []
        for j in range(len(gpa)):
            weighted_sum.append(num_students[j]*gpa[j])
        avg_gpa = sum(weighted_sum) / total
        As = num_students[0] / total

        #print("Year  Instructor      avg gpa   +As  As  B+s Bs  B-s")
        print("{}  {}  | {} | {}  | {}  ".format(years[i],instructor,(avg_gpa),total,num_students))
        #print(instructor)
        #print(num_students)
        #  print("Average GPA of Year {}: {} and % of students getting 4.00 is {} and total number of students are {}".format(instructor, avg_gpa, As, total))
    
        #print(df_year)

2010-fa  Monrad, Ditlev  | 2.6155102040816325 | 98  | [17, 6, 8, 18, 7, 9, 12, 5, 6, 5, 1, 4]
2010-fa  Hua, Lanqing  | 3.0329651162790694 | 172  | [39, 23, 25, 23, 18, 13, 16, 3, 6, 5, 1, 0]
2010-sp  Zhong, Wenxuan  | 3.4488043478260866 | 92  | [50, 0, 15, 12, 4, 5, 2, 3, 0, 0, 0, 1]
2010-sp  Ma, Ping  | 3.4897530864197526 | 162  | [91, 0, 0, 60, 1, 0, 8, 1, 0, 1, 0, 0]
2010-su  Monrad, Ditlev  | 3.142553191489362 | 47  | [19, 7, 2, 6, 4, 1, 2, 2, 0, 1, 0, 3]
2011-fa  Huang, Yinxiao  | 2.8803645833333333 | 192  | [56, 18, 10, 32, 19, 15, 19, 0, 5, 2, 2, 14]
2011-fa  Stepanov, Alexey G  | 3.151957671957672 | 189  | [54, 25, 20, 46, 8, 6, 11, 11, 2, 5, 0, 1]
2011-sp  Stepanov, Alexei G  | 2.934186046511628 | 172  | [34, 17, 30, 28, 16, 13, 10, 14, 0, 6, 0, 4]
2011-sp  Hua, Lanqing  | 2.6346951219512196 | 164  | [32, 9, 5, 38, 18, 7, 23, 7, 2, 11, 7, 5]
2011-su  Huang, Yinxiao  | 2.8803645833333333 | 192  | [56, 18, 10, 32, 19, 15, 19, 0, 5, 2, 2, 14]
2011-su  Stepanov, Alexey G  | 3.151957671957672 | 189  | [54, 25, 20, 46, 8, 6, 11, 11, 2, 5, 0, 1]
2012-fa  Huang, Yinxiao  | 2.8370689655172416 | 174  | [37, 13, 12, 58, 7, 18, 9, 0, 0, 2, 5, 13]
2012-fa  Culpepper, Steven A  | 2.6176470588235294 | 170  | [53, 11, 12, 15, 9, 10, 17, 4, 8, 5, 6, 20]
2012-sp  Monrad, Ditlev  | 3.3247500000000003 | 40  | [23, 2, 2, 5, 0, 3, 2, 0, 0, 1, 0, 2]
2012-su  Monrad, Ditlev  | 3.3247500000000003 | 40  | [23, 2, 2, 5, 0, 3, 2, 0, 0, 1, 0, 2]
2013-fa  Huang, Yinxiao  | 3.0366336633663367 | 101  | [24, 14, 10, 26, 9, 5, 4, 1, 1, 0, 2, 5]
2013-fa  Culpepper, Steven A  | 2.9045081967213116 | 122  | [40, 12, 15, 10, 9, 6, 8, 7, 3, 0, 1, 11]
2013-fa  Chen, Xiaohui  | 3.3602678571428575 | 112  | [28, 21, 22, 22, 12, 6, 1, 0, 0, 0, 0, 0]
2013-sp  Stepanov, Alexey G  | 3.213883495145631 | 206  | [84, 25, 22, 26, 11, 6, 7, 9, 1, 8, 2, 5]
2013-sp  nan  | nan | 0.0  | [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
2013-su  Stepanov, Alexey G  | 3.1145714285714283 | 70  | [25, 8, 5, 9, 7, 6, 4, 1, 0, 2, 1, 2]
2014-fa  Stepanov, Alexey G  | 2.9986284289276814 | 401  | [114, 42, 54, 38, 48, 27, 21, 23, 4, 17, 7, 6]
2014-fa  Dalpiaz, David M  | 2.9092537313432842 | 201  | [57, 33, 21, 17, 14, 12, 9, 10, 3, 6, 7, 12]
2014-sp  Stepanov, Alexey G  | 2.998028169014085 | 426  | [129, 44, 52, 46, 49, 18, 17, 29, 8, 20, 4, 10]
2014-sp  Chen, Xiaohui  | 2.7856701030927837 | 194  | [28, 25, 22, 29, 29, 18, 18, 10, 1, 1, 3, 10]
2014-su  Stepanov, Alexey G  | 3.2455882352941177 | 68  | [32, 9, 4, 8, 3, 1, 2, 3, 0, 3, 0, 3]
2015-fa  Stepanov, Alexey G  | 3.1009540636042403 | 566  | [162, 81, 86, 70, 45, 26, 32, 25, 0, 25, 3, 11]
2015-fa  Fellouris, Georgios  | 3.0024161073825506 | 149  | [35, 17, 23, 22, 20, 8, 10, 4, 2, 1, 0, 7]
2015-sp  Dalpiaz, David M  | 2.9415934065934066 | 182  | [46, 19, 25, 24, 19, 13, 8, 11, 3, 5, 3, 6]
2015-sp  Guerrier, Stephane  | 3.029637305699482 | 193  | [58, 27, 25, 22, 13, 9, 13, 11, 2, 1, 1, 11]
2015-sp  Stepanov, Alexey G  | 3.0458823529411765 | 204  | [57, 23, 28, 22, 19, 16, 18, 10, 0, 9, 0, 2]
2015-su  Stepanov, Alexey G  | 3.347857142857143 | 140  | [62, 18, 14, 20, 8, 4, 6, 2, 0, 2, 0, 4]
2016-fa  Ravat, Uma V  | 3.20192513368984 | 187  | [61, 31, 15, 34, 17, 8, 9, 2, 1, 1, 2, 6]
2016-fa  Culpepper, Steven A  | 3.2754078549848944 | 331  | [103, 73, 43, 33, 32, 18, 9, 6, 3, 2, 1, 8]
2016-fa  Dalpiaz, David M  | 3.0744041450777204 | 193  | [61, 22, 23, 24, 19, 14, 8, 6, 3, 6, 1, 6]
2016-sp  Zhu, Ruoqing  | 3.2385602094240835 | 382  | [146, 64, 40, 42, 19, 18, 13, 13, 7, 4, 8, 8]
2016-sp  Chen, Xiaohui  | 2.873886010362694 | 193  | [25, 30, 28, 30, 19, 24, 17, 3, 8, 1, 6, 2]
2017-fa  Dalpiaz, David M  | 3.1643575418994403 | 179  | [59, 39, 22, 21, 9, 2, 4, 4, 3, 3, 1, 12]
2017-fa  Chatterjee, Sabyasachi  | 2.8304294478527607 | 163  | [34, 15, 23, 23, 12, 10, 21, 10, 2, 4, 6, 3]
2017-fa  Stepanov, Alexey G  | 2.9807978723404247 | 188  | [65, 17, 17, 18, 23, 10, 11, 6, 3, 6, 1, 11]
2017-fa  Ravat, Uma V  | 2.993208556149732 | 187  | [56, 25, 22, 22, 18, 9, 4, 9, 3, 8, 1, 10]
2017-sp  Ravat, Uma V  | 3.426237113402062 | 194  | [97, 25, 21, 19, 8, 6, 5, 3, 3, 3, 1, 3]
2017-sp  Chen, Xiaohui  | 3.074157894736843 | 190  | [36, 32, 30, 29, 27, 12, 10, 6, 1, 1, 5, 1]

<ipython-input-12-6e99e169fc82>:31: RuntimeWarning: invalid value encountered in double_scalars
  avg_gpa = sum(weighted_sum) / total
<ipython-input-12-6e99e169fc82>:32: RuntimeWarning: invalid value encountered in double_scalars
  As = num_students[0] / total

2017-sp  Fellouris, Georgios  | 3.1269886363636363 | 176  | [54, 14, 25, 26, 25, 12, 3, 8, 5, 1, 0, 3]
2017-sp  Culpepper, Steven A  | 2.936081871345029 | 171  | [25, 38, 28, 21, 18, 9, 8, 6, 5, 4, 1, 8]
2017-su  Stepanov, Alexey G  | 3.556133333333334 | 75  | [38, 14, 5, 8, 4, 1, 4, 1, 0, 0, 0, 0]
2018-fa  Lee, Hyoeun  | 2.768944444444444 | 180  | [33, 25, 18, 23, 19, 9, 20, 9, 7, 7, 4, 6]
2018-fa  Ravat, Uma V  | 2.967400530503978 | 377  | [121, 42, 40, 53, 22, 17, 26, 11, 8, 7, 3, 27]
2018-fa  Chen, Xiaohui  | 3.1801136363636373 | 176  | [31, 36, 34, 34, 17, 12, 3, 2, 1, 3, 2, 1]
2018-sp  Dalpiaz, David M  | 3.3423280423280426 | 189  | [89, 22, 20, 24, 9, 4, 4, 3, 3, 4, 3, 4]
2018-sp  Ravat, Uma V  | 3.2490355329949243 | 197  | [82, 24, 18, 26, 16, 7, 9, 2, 1, 3, 2, 7]
2018-sp  Zhu, Ruoqing  | 3.2335233160621764 | 193  | [72, 28, 24, 22, 14, 7, 7, 8, 2, 1, 4, 4]
2018-sp  Fellouris, Georgios  | 2.9685625 | 160  | [47, 9, 26, 27, 9, 11, 6, 10, 0, 8, 0, 7]
2018-su  Stepanov, Alexey G  | 3.2851315789473685 | 76  | [30, 11, 10, 8, 2, 4, 5, 2, 0, 4, 0, 0]
2019-fa  Ravat, Uma V  | 3.197032085561496 | 374  | [163, 34, 38, 41, 21, 17, 16, 11, 10, 6, 6, 11]
2019-fa  Lee, Hyoeun  | 2.9718954248366014 | 153  | [49, 18, 27, 10, 11, 5, 6, 4, 1, 5, 10, 7]
2019-fa  Chatterjee, Sabyasachi  | 3.1926923076923077 | 26  | [15, 0, 0, 1, 1, 0, 7, 2, 0, 0, 0, 0]
2019-sp  Ravat, Uma V  | 3.2316890080428946 | 373  | [161, 41, 35, 45, 27, 13, 16, 5, 4, 8, 5, 13]
2019-sp  Fellouris, Georgios  | 2.7789726027397257 | 146  | [40, 16, 10, 18, 8, 6, 19, 9, 5, 0, 7, 8]
2019-sp  Lan, Shiwei  | 2.950774193548387 | 155  | [39, 24, 16, 19, 14, 13, 10, 4, 4, 2, 2, 8]
2019-su  Stepanov, Alexey G  | 3.322280701754386 | 57  | [25, 7, 3, 10, 5, 0, 2, 2, 0, 3, 0, 0]
2020-fa  Yu, Albert  | 3.320366972477064 | 654  | [293, 79, 59, 76, 38, 24, 39, 25, 3, 4, 0, 14]
2020-sp  Nguyen, Ha Khanh  | 3.4753125000000002 | 160  | [74, 26, 16, 18, 11, 6, 7, 0, 0, 0, 0, 2]
2020-sp  Yu, Albert  | 3.769942857142857 | 525  | [369, 75, 21, 33, 15, 4, 4, 1, 0, 0, 0, 3]
2020-su  Stepanov, Alexey G  | 3.2374712643678163 | 87  | [46, 4, 9, 8, 4, 3, 3, 1, 0, 3, 1, 5]
2020-wi  Stepanov, Alexey G  | 3.2374712643678163 | 87  | [46, 4, 9, 8, 4, 3, 3, 1, 0, 3, 1, 5]
2021-fa  Nguyen, Ha Khanh  | 3.152173913043478 | 184  | [83, 16, 18, 14, 11, 12, 6, 5, 5, 1, 3, 10]
2021-fa  Unger, David  | 2.996938775510204 | 98  | [28, 17, 9, 15, 6, 3, 6, 1, 4, 1, 2, 6]
2021-fa  Yu, Albert  | 3.640322580645161 | 279  | [189, 21, 29, 14, 5, 4, 3, 4, 3, 4, 1, 2]
2021-sp  Yu, Albert  | 3.4325806451612904 | 589  | [347, 55, 37, 37, 25, 19, 22, 14, 6, 8, 5, 14]
2021-su  Nguyen, Ha Khanh  | 2.999761904761905 | 84  | [33, 6, 8, 11, 2, 7, 4, 3, 2, 1, 0, 7]

In [26]:
number,name = input_class()
year = input()
name = name.upper()


new_df = df.loc[(df['Number'] == number)  & (df['Subject'] == name)]

years = new_df.YearTerm.unique()
df_year = new_df.loc[(new_df['YearTerm'] == year)]
instructors = df_year.Primary_Instructor.unique()
df_year
for instructor in instructors:
    df_instructor = df_year.loc[(df_year['Primary_Instructor']) == instructor]
    new = (df_instructor.sum(axis = 0, skipna = True))
        
    #print(df_year)
    
    num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        
    gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00]
    total = sum(num_students, 0)
    
    weighted_sum = []
    for j in range(len(gpa)):
        weighted_sum.append(num_students[j]*gpa[j])
    avg_gpa = sum(weighted_sum) / total
    As = num_students[0] / total

    #print("Year  Instructor      avg gpa   +As  As  B+s Bs  B-s")
    print("{}  {}  | {} | {}  | {}  ".format(year,instructor,(avg_gpa),total,num_students))

2021-fa  Nguyen, Ha Khanh  | 3.152173913043478 | 184  | [83, 16, 18, 14, 11, 12, 6, 5, 5, 1, 3, 10]
2021-fa  Unger, David  | 2.996938775510204 | 98  | [28, 17, 9, 15, 6, 3, 6, 1, 4, 1, 2, 6]
2021-fa  Yu, Albert  | 3.640322580645161 | 279  | [189, 21, 29, 14, 5, 4, 3, 4, 3, 4, 1, 2]

In [24]:
def createData(number, name, year):
    name = name.upper()
    #print(number)
    #print(name)
    new_df = df.loc[(df['Number'] == number)  & (df['Subject'] == name)]
    #print(new_df)
    data = []
    years = new_df.YearTerm.unique()
    df_year = new_df.loc[(new_df['YearTerm'] == year)]
    instructors = df_year.Primary_Instructor.unique()
    df_year
    for instructor in instructors:
        df_instructor = df_year.loc[(df_year['Primary_Instructor']) == instructor]
        new = (df_instructor.sum(axis = 0, skipna = True))
        
        #print(df_year)
    
        num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        
        gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00]
        total = sum(num_students, 0)
    
        weighted_sum = []
        for j in range(len(gpa)):
            weighted_sum.append(num_students[j]*gpa[j])
        avg_gpa = sum(weighted_sum) / total
        As = num_students[0] / total

        #print("Year  Instructor      avg gpa   +As  As  B+s Bs  B-s")
        print("{}  {}  | {} | {}  | {}  ".format(year,instructor,(avg_gpa),total,num_students))
        
        tmp = []
        tmp.append(year)
        tmp.append(instructor)
        tmp.append(avg_gpa)
        data.append(tmp)

    #print(data)    
    df_classyear = pd.DataFrame(data, columns = ['YearTerm', 'Instructor', 'AvgGPA'])
    return df_classyear

In [25]:
df2 = createData('400', 'STAT','2021-fa', df)
print(df2)

Empty DataFrame
Columns: [Year, Term, YearTerm, Subject, Number, Course_Title, Sched Type, A+, A, A-, B+, B, B-, C+, C, C-, D+, D, D-, F, W, Primary_Instructor]
Index: []

[0 rows x 22 columns]
Empty DataFrame
Columns: [YearTerm, Instructor, AvgGPA]
Index: []
Empty DataFrame
Columns: [YearTerm, Instructor, AvgGPA]
Index: []