In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('uiuc-gpa-dataset.csv')

df = df.rename(columns={'Course Title': 'Course_Title'})
df = df.rename(columns={'Primary Instructor': 'Primary_Instructor'})
df

,Year,Term,YearTerm,Subject,Number,Course_Title,Sched Type,A+,A,A-,...,B-,C+,C,C-,D+,D,D-,F,W,Primary_Instructor
0,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,2,14,2,...,3,0,1,0,0,0,0,0,0,"Zheng, Reanne"
1,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,15,0,...,1,0,2,0,0,0,0,1,0,"Atienza, Paul Michael L"
2,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,OD,7,4,1,...,0,2,3,0,0,1,0,1,0,"Wang, Yu"
3,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,1,18,0,...,1,0,0,0,0,0,0,0,0,"Zheng, Reanne"
4,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,16,1,...,1,0,2,0,0,0,0,0,0,"Atienza, Paul Michael L"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61552,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,0,1,3,0,0,0,2,1,"Stepanov, Alexei G"
61553,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,0,0,"Unger, David"
61554,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,7,5,1,1,0,2,0,1,0,"Morgan, William T"
61555,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,0,3,3,2,0,0,1,1,0,"Ott-Monsivais, Stephanie"
61556,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,1,0,4,0,0,1,0,2,0,"Keane, Richard D"

In [2]:
def input_class():
    class_string = input("Enter Class >>>")
    num = int(class_string.split()[1])
    name = class_string.split(' ')[0]
    return num,name

def linegraph(gpa, num_students, proff):
    fig = plt.figure()
    ax = fig.add_subplot(1, 1, 1)
    ax.plot(gpa, num_students, color='tab:blue')
    ax.set_title(proff)
    plt.show()

def scatterPlot(gpa, num_students, proffs):
    fig, ax = plt.subplots()
    for prof in proffs:
        scale = 200.0 * np.random.rand(n)
        ax.scatter(x, y, c=color, s=scale, label=color,
               alpha=0.3, edgecolors='none')

def sort_by_instructor():
    proffs = new_df.Primary_Instructor.unique()
    print(proffs)
    for prof in proffs:
        df_byProff = (df.loc[(df['Primary_Instructor'] == prof) ])
    
        new = df_byProff.sum(axis = 0, skipna = True)
        num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00, 0.00]

def sort_by_year():
    years = new_df.Year.unique()
    print(years)
    total = 0
    for year in years:
        df_year = (df.loc[(df['Year'] == year) ])
    
        new = df_year.sum(axis = 0, skipna = True)
        num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00, 0.00]
        total = sum(num_students) + total
    print(total)

def cumulative(num_students):
    total = 0 
    cum = []
    for i in range(13):
        if i == 0:
            cum.append(num_students[13-i])
            
        cum.append(num_students[13-i] + cum[13-1])
        cum.reverse
    return cum

In [3]:
#user input    
num,sub = input_class()
#sort by class
new_df = (df.loc[(df['Number'] == num)  & (df['Subject'] == sub)])
#list of years
years = new_df.Year.unique()
years.sort()
avg = 0
for year in years:
    df_year = (new_df.loc[(df['Year'] == year) ])
  
    new = (df_year.sum(axis = 0, skipna = True))
    #print(df_year)
    
    num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
    gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00]
    total = sum(num_students, 0)
    
    weighted_sum = []
    for i in range(len(gpa)):
        weighted_sum.append(num_students[i]*gpa[i])
    avg_gpa = sum(weighted_sum) / total
    As = num_students[0] / total

    #print("Average GPA of Year {}: {} and % of students getting 4.00 is {} and total number of students are {}".format(year, avg_gpa, As, total))
    avg = avg + avg_gpa
    
new_df

#print("Average" + str(avg / len(years)))

Empty DataFrame
Columns: [Year, Term, YearTerm, Subject, Number, Course_Title, Sched Type, A+, A, A-, B+, B, B-, C+, C, C-, D+, D, D-, F, W, Primary_Instructor]
Index: []

[0 rows x 22 columns]

In [4]:
number,name = input_class()
name = name.upper()

new_df = df.loc[(df['Number'] == number)  & (df['Subject'] == name)]
years = new_df.YearTerm.unique()
years.sort()
instructors = new_df.Primary_Instructor.unique()

#
for i in range(len(years)):
    df_year = new_df.loc[(new_df['YearTerm'] == years[i])]
    instructors = df_year.Primary_Instructor.unique()
    for instructor in instructors:
        #print(i)
        #print(years[i])
        #df_year = new_df.loc[(new_df['Primary_Instructor'] == instructor) & (new_df['Year'] == years[i])]
        #df_year = new_df.loc[& (new_df['Year'] == year)]
        df_instructor = df_year.loc[(df_year['Primary_Instructor']) == instructor]
        new = (df_instructor.sum(axis = 0, skipna = True))
        
        #print(df_year)
    
        num_students = [new['A+']+new['A'], new['A-'], new['B+'], new['B'], new['B-'], new['C+'], new['C'], new['C-'], new['D+'], new['D'], new['D-'], new['F']]
        
        gpa = [4.00, 3.67, 3.33, 3.00, 2.67, 2.33, 2.00, 1.67, 1.33, 1.00, 0.67, 0.00]
        total = sum(num_students, 0)
    
        weighted_sum = []
        for j in range(len(gpa)):
            weighted_sum.append(num_students[j]*gpa[j])
        avg_gpa = sum(weighted_sum) / total
        As = num_students[0] / total

        #print("Year  Instructor      avg gpa   +As  As  B+s Bs  B-s")
        print("{}  {}  | {} | {}  | {}  ".format(years[i],instructor,(avg_gpa),total,num_students))
        #print(instructor)
        #print(num_students)
        #  print("Average GPA of Year {}: {} and % of students getting 4.00 is {} and total number of students are {}".format(instructor, avg_gpa, As, total))
    
        #print(df_year)

2010-fa  Heeren, Cinda  | 2.7943181818181815 | 264  | [73, 13, 17, 65, 5, 5, 38, 14, 0, 22, 0, 12]
2010-sp  Kassa, Debessay F  | 2.4932 | 25  | [5, 0, 2, 7, 1, 0, 6, 0, 0, 0, 0, 4]
2010-sp  Karahan, Ibrahim  | 2.228627450980392 | 51  | [10, 1, 2, 9, 1, 2, 12, 0, 0, 5, 0, 9]
2010-sp  Earls, John C  | 2.913518518518518 | 54  | [13, 3, 4, 16, 2, 2, 9, 0, 0, 5, 0, 0]
2010-sp  Singh, Varun K  | 2.463913043478261 | 23  | [5, 2, 1, 2, 1, 1, 5, 0, 0, 5, 0, 1]
2010-su  Earls, John C  | 2.7776190476190474 | 21  | [6, 1, 2, 4, 0, 1, 3, 1, 0, 2, 0, 1]
2011-fa  Heeren, Cinda  | 2.9744923076923073 | 325  | [104, 20, 19, 72, 16, 21, 34, 17, 0, 10, 0, 12]
2011-sp  Heeren, Cinda  | 3.0521551724137934 | 232  | [72, 35, 12, 49, 11, 9, 14, 5, 0, 18, 0, 7]
2011-su  Heeren, Cinda  | 2.9744923076923073 | 325  | [104, 20, 19, 72, 16, 21, 34, 17, 0, 10, 0, 12]
2012-fa  Heeren, Cinda  | 3.003018867924528 | 371  | [112, 58, 23, 70, 14, 13, 39, 0, 0, 21, 0, 21]
2012-sp  Toole, John D  | 2.6003636363636367 | 55  | [13, 6, 4, 8, 2, 3, 4, 5, 0, 3, 0, 7]
2012-su  Toole, John D  | 2.6003636363636367 | 55  | [13, 6, 4, 8, 2, 3, 4, 5, 0, 3, 0, 7]
2013-fa  Heeren, Cinda  | 3.1268627450980393 | 459  | [170, 61, 24, 61, 42, 23, 30, 13, 0, 21, 0, 14]
2013-sp  Heeren, Cinda  | 2.851329923273657 | 391  | [92, 75, 22, 49, 25, 17, 56, 0, 0, 33, 0, 22]
2013-su  Massung, Sean A  | 2.7976785714285723 | 56  | [15, 4, 6, 7, 5, 5, 1, 4, 3, 2, 2, 2]
2014-fa  Heeren, Cinda  | 2.840608519269777 | 493  | [151, 48, 32, 76, 29, 29, 37, 10, 0, 50, 0, 31]
2014-sp  Heeren, Cinda  | 2.936912878787879 | 528  | [165, 44, 56, 74, 39, 32, 40, 12, 0, 42, 0, 24]
2014-su  Geigle, Chase A  | 2.882394366197183 | 71  | [19, 5, 8, 13, 3, 3, 10, 1, 4, 2, 1, 2]
2015-fa  Heeren, Cinda  | 3.0450850340136055 | 588  | [183, 84, 49, 95, 32, 29, 46, 15, 0, 32, 0, 23]
2015-sp  Heeren, Cinda  | 3.2442752293577986 | 545  | [197, 109, 64, 47, 26, 28, 23, 10, 14, 10, 0, 17]
2015-su  Geigle, Chase A  | 2.8375213675213677 | 234  | [56, 22, 32, 40, 14, 14, 16, 8, 6, 8, 2, 16]
2016-fa  Heeren, Cinda  | 3.2407417974322392 | 701  | [322, 87, 54, 73, 25, 30, 47, 0, 0, 35, 0, 28]
2016-sp  Heeren, Cinda  | 3.181719858156028 | 564  | [226, 83, 40, 76, 24, 20, 42, 0, 0, 30, 0, 23]
2016-sp  Yershova, Ganna  | 2.8363380281690143 | 71  | [17, 14, 5, 10, 6, 1, 6, 0, 0, 5, 0, 7]
2017-fa  Fagen-Ulmschnei, Wade A  | 3.053664772727273 | 704  | [322, 54, 46, 57, 33, 28, 42, 17, 24, 23, 28, 30]
2017-sp  Heeren, Cinda  | 3.0913153961136017 | 669  | [331, 55, 39, 53, 27, 16, 44, 0, 0, 56, 0, 48]
2018-fa  Fagen-Ulmschnei, Wade A  | 3.4170731707317064 | 697  | [433, 41, 45, 44, 22, 28, 22, 15, 6, 9, 11, 21]
2018-sp  Fagen-Ulmschnei, Wade A  | 3.1875288303130147 | 607  | [331, 41, 32, 43, 33, 15, 24, 12, 7, 13, 17, 39]
2019-fa  Evans, Graham C  | 3.4420264900662247 | 755  | [491, 48, 43, 38, 19, 23, 20, 17, 9, 10, 10, 27]
2019-sp  Zilles, Craig  | 3.182030567685589 | 458  | [255, 34, 29, 25, 15, 12, 12, 11, 13, 10, 5, 37]
2020-fa  Evans, Graham C  | 3.753430493273543 | 892  | [720, 46, 30, 30, 12, 12, 12, 7, 6, 5, 1, 11]
2021-fa  Evans, Graham C  | 3.4673958333333332 | 960  | [647, 62, 56, 38, 20, 26, 21, 17, 12, 9, 5, 47]
2021-sp  Evans, Graham C  | 3.319404553415061 | 571  | [356, 34, 28, 19, 21, 15, 24, 11, 15, 15, 6, 27]